const AllCollection = [
    {
        imgSrc: "/stories/desktop/mountains.jpg",
        date:"April 16th 2020",
        title: "The Mountains",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/cityscapes.jpg",
        date:"April 16th 2020",
        title: "Sunset Cityscapes",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/18-days-voyage.jpg",
        date:"April 16th 2020",
        title: "18 Days Voyage",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/architecturals.jpg",
        date:"April 16th 2020",
        title: "Architecturals",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/world-tour.jpg",
        date:"April 16th 2020",
        title: "World Tour 2019",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/cityscapes.jpg",
        date:"April 16th 2020",
        title: "Sunset Cityscapes",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/18-days-voyage.jpg",
        date:"April 16th 2020",
        title: "18 Days Voyage",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/architecturals.jpg",
        date:"April 16th 2020",
        title: "Architecturals",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/mountains.jpg",
        date:"April 16th 2020",
        title: "The Mountains",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/cityscapes.jpg",
        date:"April 16th 2020",
        title: "Sunset Cityscapes",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/18-days-voyage.jpg",
        date:"April 16th 2020",
        title: "18 Days Voyage",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/architecturals.jpg",
        date:"April 16th 2020",
        title: "Architecturals",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/mountains.jpg",
        date:"April 16th 2020",
        title: "The Mountains",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/cityscapes.jpg",
        date:"April 16th 2020",
        title: "Sunset Cityscapes",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/18-days-voyage.jpg",
        date:"April 16th 2020",
        title: "18 Days Voyage",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
    {
        imgSrc: "/stories/desktop/architecturals.jpg",
        date:"April 16th 2020",
        title: "Architecturals",
        author: "by John Appleseed",
        readStoryText: "READ STORY",
    },
  ];